import os
from dataclasses import dataclass

import cv2
import matplotlib.pyplot as plt
import numpy as np
import torch

from src.image_utils import (
    add_scale_bar,
    convert_area_pixels_to_mm2,
    is_border_touch_acceptable,
)
from src.io_utils import get_subtitles, save_mask_area
from src.logger_utils import ENABLE_PLOT_DISPLAY, print_green


@dataclass
class PlotData:
    stage2_image: object
    preprocessed_image_color: object
    mask_contour: object
    mask_area: float
    path: str
    ground_truth: str
    result_query_stage1: str
    result_query_stage2: str
    is_valid: str
    acceptable_segmentation: bool


@dataclass
class PlotPaths:
    AREAS_JSON_PATH: str
    PLOTS_SAVE_PATH: str
    PLOTS_SAVE_PATH_FAILED: str
    MASK_SAVE_PATH: str
    MASK_SAVE_PATH_FAILED: str


def plot_pipeline_steps(plot_data: "PlotData", plot_paths: "PlotPaths"):
    """
    Saves and visualizes an analytical collage of the intermediate pipeline steps,
    such as preprocessing, masking, segmentation, and bounding box placement.

    Args:
        plot_data (PlotData): Data transfer object holding intermediate pipeline tensors/images.
        plot_paths (PlotPaths): Data transfer object containing output directory paths.
    """
    # Unpack incoming objects
    stage2_image = plot_data.stage2_image

    # Add scale bar to the original image
    stage2_image = add_scale_bar(stage2_image, um_per_pixel=7.38, target_mm=1.0)
    preprocessed_image_color = getattr(plot_data, "preprocessed_image_color", None)
    mask_contour = plot_data.mask_contour
    mask_area = plot_data.mask_area
    mask_area_mm2 = convert_area_pixels_to_mm2(mask_area, mm_per_pixel=0.00738)
    path = plot_data.path
    ground_truth = plot_data.ground_truth
    result_query_stage1 = plot_data.result_query_stage1
    result_query_stage2 = plot_data.result_query_stage2
    is_valid = plot_data.is_valid

    AREAS_JSON_PATH = plot_paths.AREAS_JSON_PATH
    PLOTS_SAVE_PATH = plot_paths.PLOTS_SAVE_PATH
    PLOTS_SAVE_PATH_FAILED = plot_paths.PLOTS_SAVE_PATH_FAILED
    MASK_SAVE_PATH = plot_paths.MASK_SAVE_PATH
    MASK_SAVE_PATH_FAILED = plot_paths.MASK_SAVE_PATH_FAILED

    # Extract class_id and image_id and save area
    class_id, image_id = get_subtitles(path)
    save_mask_area(class_id, image_id, mask_area_mm2, AREAS_JSON_PATH)

    # Create a figure with three subplots using fixed width ratios so the center mask
    # panel remains narrower and the cropped image has more space. Reserve extra
    # bottom margin for the textual annotations so they never overlap the first subplot.
    fig, axes = plt.subplots(
        1, 3, figsize=(20, 8), gridspec_kw={"width_ratios": [1.0, 1.0, 1.0]}
    )
    fig.suptitle(f"Class: {class_id}, File: {image_id}", fontsize=14)

    # Plot the original color image
    axes[0].imshow(stage2_image)
    axes[0].set_title("Original Image")
    axes[0].axis("off")

    # Plot the mask
    axes[1].imshow(mask_contour, cmap="gray")
    axes[1].set_title("Output mask generated by Prompt Generator")
    axes[1].axis("off")
    axes[1].annotate(
        f"Area: {mask_area_mm2:.3f} (mm²)",
        xy=(0.5, 0),
        xycoords="axes fraction",
        xytext=(0, -5),
        textcoords="offset points",
        ha="center",
        va="top",
        fontsize=10,
        color="black",
    )

    # Crop the original image using the mask
    cropped = cv2.bitwise_and(stage2_image, stage2_image, mask=mask_contour)
    # Find contours from the mask
    contours, _ = cv2.findContours(
        mask_contour, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
    )
    # Ensure cropped is 3-channel BGR for drawing/display
    if cropped.ndim == 2 or (cropped.ndim == 3 and cropped.shape[2] == 1):
        cropped_bgr = cv2.cvtColor(cropped, cv2.COLOR_GRAY2BGR)
    else:
        cropped_bgr = cropped.copy()
    # Draw the contours in green
    cv2.drawContours(cropped_bgr, contours, -1, (0, 255, 0), thickness=1)

    # Plot the cropped image with contour
    axes[2].imshow(cropped_bgr)
    axes[2].set_title("Original Image Cropped with Prompt Generator mask")
    axes[2].axis("off")

    # Border-touching check and annotation
    acceptable_segmentation = is_border_touch_acceptable(
        mask_contour, tolerance_percent=10.0
    )

    # Derive pipeline-level status from the provided is_valid field (if available)
    # This mirrors the behavior in sam2-pipeline_v2.py
    # If is_valid wasn't passed, fall back to using acceptable_segmentation
    if is_valid is None:
        pipeline_result = acceptable_segmentation
    else:
        pipeline_result = is_valid == "matched"
    status_text_top = "Approved" if pipeline_result else "Rejected"
    status_color = "green" if pipeline_result else "red"
    # Centered status text (sup-sup-title) below the main suptitle
    fig.text(
        0.5,
        0.94,
        status_text_top,
        ha="center",
        va="center",
        fontsize=12,
        color=status_color,
        fontweight="bold",
        transform=fig.transFigure,
    )

    # Single-line border cross check annotation matching v2 style
    axes[2].annotate(
        f"border cross check: {'Passed' if acceptable_segmentation else 'Rejected'}",
        xy=(0.5, 0),
        xycoords="axes fraction",
        xytext=(0, -5),
        textcoords="offset points",
        ha="center",
        va="top",
        fontsize=10,
        color="black",
    )

    # Add text info about classes
    text_real = f"GT class: {ground_truth}"
    text_cnn = f"CNN class: {result_query_stage1}"
    text_sam2 = f"OpenCV class: {result_query_stage2 if result_query_stage2 is not None else 'N/A'}"
    color_cnn = "red" if result_query_stage1 != ground_truth else "black"
    color_sam2 = (
        "red"
        if result_query_stage2 is not None and result_query_stage2 != ground_truth
        else "black"
    )

    fig.text(
        0.02,
        0.02,
        text_sam2,
        ha="left",
        va="bottom",
        fontsize=10,
        color=color_sam2,
        transform=fig.transFigure,
    )
    fig.text(
        0.02,
        0.05,
        text_cnn,
        ha="left",
        va="bottom",
        fontsize=10,
        color=color_cnn,
        transform=fig.transFigure,
    )
    fig.text(
        0.02,
        0.08,
        text_real,
        ha="left",
        va="bottom",
        fontsize=10,
        color="black",
        transform=fig.transFigure,
    )

    # Reserve bottom area for fig.text annotations so they don't overlap subplot axes.
    # rect = (left, bottom, right, top)
    plt.tight_layout(rect=(0, 0.15, 1, 0.92))

    # Build filenames and save paths
    base_image_id, _ = os.path.splitext(image_id)
    if pipeline_result:
        save_dir = os.path.join(PLOTS_SAVE_PATH, class_id)
        os.makedirs(save_dir, exist_ok=True)
        save_file_path = os.path.join(save_dir, f"{base_image_id}.png")

        mask_save_dir = os.path.join(MASK_SAVE_PATH, class_id)
        os.makedirs(mask_save_dir, exist_ok=True)
        mask_save_file_path = os.path.join(mask_save_dir, f"{base_image_id}.jpg")
    else:
        save_failed_dir = os.path.join(PLOTS_SAVE_PATH_FAILED, class_id)
        os.makedirs(save_failed_dir, exist_ok=True)
        save_file_path = os.path.join(save_failed_dir, f"{base_image_id}.png")

        mask_save_dir = os.path.join(MASK_SAVE_PATH_FAILED, class_id)
        os.makedirs(mask_save_dir, exist_ok=True)
        mask_save_file_path = os.path.join(mask_save_dir, f"{base_image_id}.jpg")

    plt.savefig(save_file_path)
    print_green(f"Saved plot to {save_file_path}")

    # Convert cropped to RGB for saving (cv2.imwrite expects BGR but original was BGR; to keep appearance consistent convert to RGB)
    try:
        cropped_rgb = cv2.cvtColor(cropped_bgr, cv2.COLOR_BGR2RGB)
    except Exception:
        cropped_rgb = cropped_bgr
    cv2.imwrite(mask_save_file_path, cropped_rgb)
    print_green(f"Saved cropped mask image to {mask_save_file_path}")

    if ENABLE_PLOT_DISPLAY:
        plt.show(block=True)

    plt.close(fig)


def visualize_pipeline_images(stage2_image, mask_contour, cropped_image):
    """
    Generates a matplotlib interactive plot inspecting pipeline stages during debug execution.

    Args:
        stage2_image (Any): The primary image supplied to the stage-2 analyzer.
        mask_contour (np.ndarray): The segmented extraction layer mask.
        cropped_image (torch.Tensor): The final tensor product of original multiplied by mask.
    """
    # Visualize stage2_image, mask_contour, and cropped (if available) in a plot window
    fig, axs = plt.subplots(1, 3, figsize=(15, 5))

    # Convert tensor to numpy array for display
    if isinstance(stage2_image, torch.Tensor):
        # Remove batch dimension and convert CHW to HWC
        image_display = stage2_image.squeeze(0).cpu().permute(1, 2, 0).numpy()
        # Denormalize if needed (assuming the image was normalized)
        image_display = np.clip(image_display, 0, 1)
    else:
        image_display = stage2_image
    axs[0].imshow(image_display)
    axs[0].set_title("stage2_image")
    axs[0].axis("off")

    # Display mask_contour
    axs[1].imshow(mask_contour, cmap="gray")
    axs[1].set_title("mask_contour")
    axs[1].axis("off")

    if cropped_image is not None:
        # Convert cropped tensor to numpy for display
        cropped_np = cropped_image.cpu().permute(1, 2, 0).numpy()
        # If the image is normalized (has negative values), denormalize it for display
        if cropped_np.min() < 0:
            # Denormalize using the same mean/std values used in normalization
            mean = np.array([0.0418, 0.0353, 0.0409])
            std = np.array([0.0956, 0.0911, 0.0769])
            cropped_np = cropped_np * std + mean
            cropped_np = np.clip(cropped_np, 0, 1)
        # Convert to display format
        if cropped_np.max() <= 1.0:
            cropped_np = (cropped_np * 255).astype(np.uint8)
        else:
            cropped_np = cropped_np.astype(np.uint8)
        axs[2].imshow(cropped_np)
        axs[2].set_title("cropped")
    else:
        axs[2].set_title("cropped (None)")
        axs[2].axis("off")

    plt.tight_layout()
    plt.show(block=True)
